### ISSUE TITLE
current status

### ISSUE THREAD

**Issue by hakor** [fpompermaier/onvif#3]
Dear developers

Just cloned your repo for a quick evaluation. 
But I cound not found any example of how to connect to a camera. 
can you give me a hint where I can find an example to connect to an ptz camera. 

Thanks

**Comment by fpompermaier** [comment]
Hi @hakor,
examples can be found here: https://github.com/fpompermaier/onvif/tree/master/onvif-java/src/test/java/org/onvif/client

Basically you have to do something like this:

```java

String deviceIp = "192.168.1.53";
String user = password = "admin";
String  profileToken = "MediaProfile000";
System.out.println("Connect to camera, please wait ...");
OnvifDevice cam = null;
try {
	cam = new OnvifDevice(deviceIp, user, password);
} catch (ConnectException | SOAPException e1) {
	System.err.println("No connection to device with ip " + deviceIp + ", please try again.");
	System.exit(0);
}
System.out.println("Connected to device " + cam.getDeviceInfo());

// get device capabilities
Capabilities cap = cam.getDevice().getCapabilities(Arrays.asList(CapabilityCategory.ALL));
System.out.println(cap.getDevice().toString())
```

**Comment by hakor** [comment]
Hi
did the following 
`
String deviceIp = "192.168.252.185:888";
String user = "admin";
String password = "password";

try {
	OnvifDevice device = new OnvifDevice(deviceIp, user, password);
} catch (Exception e) {
	e.printStackTrace();
}
`
and run it and got 
`2018-01-31 13:54:38 INFO  ReflectionServiceFactoryBean:436 - Creating Service {http://www.onvif.org/ver10/device/wsdl}DeviceService from class org.onvif.ver10.device.wsdl.Device
2018-01-31 13:54:42 INFO  ReflectionServiceFactoryBean:436 - Creating Service {http://www.onvif.org/ver10/device/wsdl}DeviceService from class org.onvif.ver10.device.wsdl.Device
2018-01-31 13:54:42 INFO  Device:273 - Outbound Message
---------------------------
ID: 1
Address: http://192.168.252.185:888/onvif/device_service
Encoding: UTF-8
Http-Method: POST
Content-Type: application/soap+xml; action="http://www.onvif.org/ver10/device/wsdl/SetSystemDateAndTime"
Headers: {Accept=[*/*]}
Payload: <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><soap:Body><SetSystemDateAndTime xmlns="http://www.onvif.org/ver10/device/wsdl" xmlns:ns2="http://www.onvif.org/ver10/schema" xmlns:ns3="http://docs.oasis-open.org/wsrf/bf-2" xmlns:ns4="http://www.w3.org/2005/08/addressing" xmlns:ns5="http://docs.oasis-open.org/wsn/b-2" xmlns:ns6="http://docs.oasis-open.org/wsn/t-1" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:ns8="http://www.w3.org/2004/08/xop/include" xmlns:ns9="http://www.w3.org/2003/05/soap-envelope"><DateTimeType>Manual</DateTimeType><DaylightSavings>false</DaylightSavings><TimeZone><ns2:TZ>GMT+01:00</ns2:TZ></TimeZone><UTCDateTime><ns2:Time><ns2:Hour>13</ns2:Hour><ns2:Minute>54</ns2:Minute><ns2:Second>42</ns2:Second></ns2:Time><ns2:Date><ns2:Year>2018</ns2:Year><ns2:Month>1</ns2:Month><ns2:Day>31</ns2:Day></ns2:Date></UTCDateTime></SetSystemDateAndTime></soap:Body></soap:Envelope>
--------------------------------------
2018-01-31 13:54:42 INFO  Device:273 - Outbound Message
---------------------------
ID: 2
Address: http://192.168.252.185:888/onvif/device_service
Encoding: UTF-8
Http-Method: POST
Content-Type: application/soap+xml; action="http://www.onvif.org/ver10/device/wsdl/GetCapabilities"
Headers: {Accept=[*/*]}
Payload: <soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope"><soap:Body><GetCapabilities xmlns="http://www.onvif.org/ver10/device/wsdl" xmlns:ns2="http://www.onvif.org/ver10/schema" xmlns:ns3="http://docs.oasis-open.org/wsrf/bf-2" xmlns:ns4="http://www.w3.org/2005/08/addressing" xmlns:ns5="http://docs.oasis-open.org/wsn/b-2" xmlns:ns6="http://docs.oasis-open.org/wsn/t-1" xmlns:xmime="http://www.w3.org/2005/05/xmlmime" xmlns:ns8="http://www.w3.org/2004/08/xop/include" xmlns:ns9="http://www.w3.org/2003/05/soap-envelope"><Category>All</Category></GetCapabilities></soap:Body></soap:Envelope>
--------------------------------------
2018-01-31 13:54:42 WARN  PhaseInterceptorChain:449 - Interceptor for {http://www.onvif.org/ver10/device/wsdl}DeviceService#{http://www.onvif.org/ver10/device/wsdl}GetCapabilities has thrown exception, unwinding now
org.apache.cxf.interceptor.Fault: Could not send Message.
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:64)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:514)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:423)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:324)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:277)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:139)
	at com.sun.proxy.$Proxy75.getCapabilities(Unknown Source)
	at de.onvif.soap.OnvifDevice.init(OnvifDevice.java:152)
	at de.onvif.soap.OnvifDevice.<init>(OnvifDevice.java:91)
	at de.dhbw.aquasi.de.dhbw.aquasi.camera.SecondTest.main(SecondTest.java:33)
Caused by: org.apache.cxf.transport.http.HTTPException: HTTP response '401: Unauthorized' when communicating with http://192.168.252.185:888/onvif/device_service
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.doProcessResponseCode(HTTPConduit.java:1608)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1615)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1559)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1356)
	at org.apache.cxf.io.CacheAndWriteOutputStream.postClose(CacheAndWriteOutputStream.java:56)
	at org.apache.cxf.io.CachedOutputStream.close(CachedOutputStream.java:216)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:653)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62)
	... 11 more
javax.xml.ws.WebServiceException: Could not send Message.
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:150)
	at com.sun.proxy.$Proxy75.getCapabilities(Unknown Source)
	at de.onvif.soap.OnvifDevice.init(OnvifDevice.java:152)
	at de.onvif.soap.OnvifDevice.<init>(OnvifDevice.java:91)
	at de.dhbw.aquasi.de.dhbw.aquasi.camera.SecondTest.main(SecondTest.java:33)
Caused by: org.apache.cxf.transport.http.HTTPException: HTTP response '401: Unauthorized' when communicating with http://192.168.252.185:888/onvif/device_service
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.doProcessResponseCode(HTTPConduit.java:1608)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponseInternal(HTTPConduit.java:1615)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.handleResponse(HTTPConduit.java:1559)
	at org.apache.cxf.transport.http.HTTPConduit$WrappedOutputStream.close(HTTPConduit.java:1356)
	at org.apache.cxf.io.CacheAndWriteOutputStream.postClose(CacheAndWriteOutputStream.java:56)
	at org.apache.cxf.io.CachedOutputStream.close(CachedOutputStream.java:216)
	at org.apache.cxf.transport.AbstractConduit.close(AbstractConduit.java:56)
	at org.apache.cxf.transport.http.HTTPConduit.close(HTTPConduit.java:653)
	at org.apache.cxf.interceptor.MessageSenderInterceptor$MessageSenderEndingInterceptor.handleMessage(MessageSenderInterceptor.java:62)
	at org.apache.cxf.phase.PhaseInterceptorChain.doIntercept(PhaseInterceptorChain.java:308)
	at org.apache.cxf.endpoint.ClientImpl.doInvoke(ClientImpl.java:514)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:423)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:324)
	at org.apache.cxf.endpoint.ClientImpl.invoke(ClientImpl.java:277)
	at org.apache.cxf.frontend.ClientProxy.invokeSync(ClientProxy.java:96)
	at org.apache.cxf.jaxws.JaxWsClientProxy.invoke(JaxWsClientProxy.java:139)
	... 4 more`

Before I used another onvif lib from here ( https://github.com/milg0/onvif-java-lib/blob/master/release/onvif-2016-02-17.jar) and I could connect with moreless the java project. 

any idea?

**Comment by fpompermaier** [comment]
Are you sure that username and password are correct?

The Exception says **HTTP response '401: Unauthorized' when communicating with http://192.168.252.185:888/onvif/device_service"**

**Comment by hakor** [comment]
well as mentioned above, I was using another older onvif client and that one worked fine.

**Comment by fpompermaier** [comment]
Why have you closed the issue? Have you tried to connect to the host without specifying the port? 
Maybe in the meantime you changed the username/password...

**Comment by hakor** [comment]
closing was accident... 

without port it does not work at all! 
>>
java.net.ConnectException: Host not available.
	at de.onvif.soap.OnvifDevice.<init>(OnvifDevice.java:84)
	at de.onvif.soap.OnvifDevice.<init>(OnvifDevice.java:107)
	at de.dhbw.aquasi.de.dhbw.aquasi.camera.SecondTest.main(SecondTest.java:34)
<<

And it works fine with the other lib (which has many drawbacks with my camera (foscam R2))...

**Comment by fpompermaier** [comment]
I'm sorry that this lib doesn't work well with your device. Would you mind to give it a try to debug and fix the issue? However the problem seems to be cause by a wrong username/password (IMHO)

**Comment by hakor** [comment]
well, in OnvifDevice, the username and password is never used in current implementation. 
The authorisation policy in method getServiceProxy is commented out. 
Did you ever test it against a secured device?

**Comment by hakor** [comment]
Does the answer mean "NO"? :-(

**Comment by fpompermaier** [comment]
Yes, it wasn't tested against a secure device. The code of this repo basically starts from the one of the repo you were using before (https://github.com/milg0/onvif-java-lib/blob/master/release/onvif-2016-02-17.jar) so I didn't test all possible devices/configurations..by the way, it is strange that it was working with that version and not with mine..I didn't change so much the connection part

**Comment by quonn77** [comment]
User and password authentication in my case need implementation of WSSE Usernametoken, I have done it on my fork.

**Comment by quonn77** [comment]
Hi Flavio, you are right but this doesn't imply that you have to save those stubs into a SCM. My fork generate the stubs as per need by means of maven, and store the source code on the standard (AFAIK) target/generated-sources folder. This allow to easily update wsdl files and avoid conflicts with no more existent stubs (...just in case...).
Usually I prefer to not put into configuration what is already generated by compilers.
