### ISSUE TITLE
XML Reader ERROR

### ISSUE THREAD

**Issue by bagabobs** [fpompermaier/onvif#4]
hi developer,

I've cloned your project and I've done build install. after I run the program code as in the example, an error occurs. here is the error
`Exception in thread "main" com.sun.xml.internal.ws.streaming.XMLStreamReaderException: XML reader error: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '.' (code 46) in prolog; expe
cted '<'
 at [row,col,system-id]: [1,1,"file:/D:/WAW/HARD/git/jse/testsuite/"]
        at com.sun.xml.internal.ws.streaming.XMLStreamReaderUtil.wrapException(XMLStreamReaderUtil.java:311)
        at com.sun.xml.internal.ws.streaming.XMLStreamReaderUtil.next(XMLStreamReaderUtil.java:84)
        at com.sun.xml.internal.ws.streaming.XMLStreamReaderUtil.nextContent(XMLStreamReaderUtil.java:154)
        at com.sun.xml.internal.ws.streaming.XMLStreamReaderUtil.nextElementContent(XMLStreamReaderUtil.java:89)
        at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.hasWSDLDefinitions(RuntimeWSDLParser.java:310)
        at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:217)
        at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:194)
        at com.sun.xml.internal.ws.wsdl.parser.RuntimeWSDLParser.parse(RuntimeWSDLParser.java:163)
        at com.sun.xml.internal.ws.client.WSServiceDelegate.parseWSDL(WSServiceDelegate.java:348)
        at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:306)
        at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:215)
        at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:196)
        at com.sun.xml.internal.ws.client.WSServiceDelegate.<init>(WSServiceDelegate.java:192)
        at com.sun.xml.internal.ws.spi.ProviderImpl.createServiceDelegate(ProviderImpl.java:104)
        at javax.xml.ws.Service.<init>(Service.java:77)
        at org.onvif.ver10.device.wsdl.DeviceService.<init>(DeviceService.java:36)
        at de.onvif.soap.OnvifDevice.init(OnvifDevice.java:147)
        at de.onvif.soap.OnvifDevice.<init>(OnvifDevice.java:91)
        at len.scadajakpro.testsuite.NewOnvifLibTest.main(NewOnvifLibTest.java:13)
Caused by: com.ctc.wstx.exc.WstxUnexpectedCharException: Unexpected character '.' (code 46) in prolog; expected '<'
 at [row,col,system-id]: [1,1,"file:/D:/WAW/HARD/git/jse/testsuite/"]
        at com.ctc.wstx.sr.StreamScanner.throwUnexpectedChar(StreamScanner.java:647)
        at com.ctc.wstx.sr.BasicStreamReader.nextFromProlog(BasicStreamReader.java:2054)
        at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1131)
        at com.sun.xml.internal.ws.util.xml.XMLStreamReaderFilter.next(XMLStreamReaderFilter.java:81)
        at com.sun.xml.internal.ws.streaming.XMLStreamReaderUtil.next(XMLStreamReaderUtil.java:65)
        ... 17 more

FAILURE: Build failed with an  exception.`

and here's a sample code I created

`public class NewOnvifLibTest {
    public static void main(String[] args) throws SOAPException, ConnectException {
        OnvifDevice device = new OnvifDevice("192.168.2.100", null, null);
        System.out.println("Device Info " + device.getDeviceInfo());
        /*
        List<Profile> listProfile = device.getMedia().getProfiles();
        for(int i=0; i<listProfile.size(); i++)
        {
            System.out.println("Profile 1 " + listProfile.get(i).getToken());
        }
        */
    }
}`

can you explain why the error occurred? and how to fix it?

**Comment by fpompermaier** [comment]
Can you debug a little bit what happens inside the onvif device con
